[package]
name = "mail-list-rss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "~1.14.0", features = ["macros", "rt-multi-thread", "net", "io-util"] }
log = { version = "0.4.14", features = ["std"] }
simple_logger = "1.15.0"
anyhow = "1.0.51"
mailin = "0.5.0"
mailparse = "0.13.6"
rss = "2.0.0"
serde = { version = "~1.0.130", features = ["derive"] }
mongodb = { version = "~2.0.2", features = ["bson-chrono-0_4", "bson-uuid-0_8"] }
chrono = { version = "~0.4.19", features = ["serde"] }
uuid = "~0.8.2"

