# fly.toml file generated for mail-list-rss on 2021-11-30T03:39:36+08:00

app = "mail-list-rss"

kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[experimental]
cmd = "mail-list-rss"

# Web service
[[services]]
internal_port = 8080
protocol      = "tcp"

[[services.ports]]
handlers = ["http"]
port     = 80

[[services.ports]]
handlers = ["tls", "http"]
port     = 443

[[services.http_checks]]
interval        = "10000"
grace_period    = "5s"
method          = "get"
path            = "/health"
protocol        = "http"
timeout         = "2000"
tls_skip_verify = false

# SMTP service
[[services]]
internal_port = 10000
protocol      = "tcp"

[[services.ports]]
port = 25

[[services.tcp_checks]]
interval     = "10000"
timeout      = "2000"
grace_period = "5s"
